set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hazard_sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hazard_sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hazard_sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hazard_sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports reset]
set_property PACKAGE_PIN U2 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]
set_property PACKAGE_PIN V17 [get_ports {hazard_sw[0]}]
set_property PACKAGE_PIN V16 [get_ports {hazard_sw[1]}]
set_property PACKAGE_PIN W16 [get_ports {hazard_sw[2]}]
set_property PACKAGE_PIN W17 [get_ports {hazard_sw[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PACKAGE_PIN U16 [get_ports {leds[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds[2]}]

set_property PACKAGE_PIN K17 [get_ports buzzer]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer]

set_property IOSTANDARD LVCMOS33 [get_ports {led_ext[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_ext[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_ext[0]}]
set_property PACKAGE_PIN A14 [get_ports {led_ext[0]}]
set_property PACKAGE_PIN A16 [get_ports {led_ext[1]}]
set_property PACKAGE_PIN B15 [get_ports {led_ext[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports silence_sw]
set_property PACKAGE_PIN T1 [get_ports silence_sw]


set_property IOSTANDARD LVCMOS33 [get_ports o_CS]
set_property IOSTANDARD LVCMOS33 [get_ports o_DC]
set_property IOSTANDARD LVCMOS33 [get_ports o_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports o_PMODEN]
set_property IOSTANDARD LVCMOS33 [get_ports o_RES]
set_property PACKAGE_PIN G3 [get_ports o_PMODEN]
set_property PACKAGE_PIN J1 [get_ports o_CS]
set_property PACKAGE_PIN H1 [get_ports o_DC]
set_property PACKAGE_PIN L2 [get_ports o_MOSI]
set_property PACKAGE_PIN K2 [get_ports o_RES]
set_property PACKAGE_PIN G2 [get_ports o_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports o_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports o_VCCEN]
set_property PACKAGE_PIN H2 [get_ports o_VCCEN]

